### ISSUE TITLE
Issue with System Assigned Managed Identity and execution from inside a VM

### ISSUE THREAD

**Issue by Josegc1989** [diecknet/Simple-Azure-VM-Start-Stop#7]
Hi, 
I'm trying to execute this script. It gives me a error:

![image](https://github.com/diecknet/Simple-Azure-VM-Start-Stop/assets/164342550/68bd135f-f2bb-4b88-ab35-3b30ab18d5e6)

I have created the custom role with the json and a Identity Managed System assigned to the custom role:

![image](https://github.com/diecknet/Simple-Azure-VM-Start-Stop/assets/164342550/d5715c61-0688-4f06-ba78-34345f0837d7)

![image](https://github.com/diecknet/Simple-Azure-VM-Start-Stop/assets/164342550/94ec1a36-8e8a-406e-8912-cb6ac8a57ab1)

![image](https://github.com/diecknet/Simple-Azure-VM-Start-Stop/assets/164342550/738a3774-ebc7-4aeb-9392-0a1547b9122e)

Do you know what am I doing bad??

Thanks!

**Comment by diecknet** [comment]
Hello,
I have only used Managed Identities with Azure Automation. Looks like your trying to run it from an Azure VM. That *should* work too, but I never tried it.
The warning that you get sounds a bit weird. Can you please try to run the script with parameters instead of waiting for the prompt? Then you can provide the SubscriptionID as a parameter.

**Comment by diecknet** [comment]
Closing because no response from user
